### ISSUE TITLE
License needs clarification (which linking exception?)

### ISSUE THREAD

**Issue by treinen** [Chris00/ocaml-cairo#15]
Hello,

the license header, for instance in the file "src/cairo.ml", says:

````
under the terms of the GNU Lesser General Public License version 3 or
later as published by the Free Software Foundation, with the special
exception on linking described in the file LICENSE
````

However, the file LICENSE.md (I guess that is the file you mean) contains an almost verbatim copy of the LGPL-3, the only difference being minor layout changes. There is no special exception on linking to be found in this file.

**Comment by Chris00** [comment]
I do no know whether the linking exception has already been combined with the LGPL 3—I'll have to investigate.  Otherwise, using LGPL 2.1 may be simpler.

**Comment by pombredanne** [comment]
This could be --IMHO-- the Ocaml exception: https://caml.inria.fr/ocaml/license.en.html and https://spdx.org/licenses/OCaml-LGPL-linking-exception.html as this makes LGPL-licensed code possible when everything is statically linked and is the common exception used in the OCaml ecosystem?

**Comment by Chris00** [comment]
I removed the linking exception.
