### ISSUE TITLE
License of tutorial.html is missing

### ISSUE THREAD

**Issue by treinen** [Chris00/ocaml-cairo#16]
Sorry to bother you again with a boring license question:

docs/tutorial.html is copyrighted Michael Urman. Has this document really been licensed by the copyright holder under the LGPL? If not, what is its license?

**Comment by Chris00** [comment]
I emailed Michael Urman and he says 

> I offered it under the GPL (v2 or later), and I consider the images to be the output from the included sample code. (Thus if you include the images, you must include code to generate them.)

So I will make clear my version is released under the GPL v3 licence.
