### ISSUE TITLE
[archimedes] - Migrate off camlp4

### ISSUE THREAD

**Issue by XVilka** [Chris00/ocaml-cairo#17]
Camlp4 release for OCaml 4.08 is the last release ever - see the [official announcement](https://discuss.ocaml.org/t/the-end-of-camlp4/4216). It is recommended to port the code to use ppx (extension points), or any external parser (like mehrir, sedlex, ocamllex, ansgtrom, etc).

http://opam.ocaml.org/packages/archimedes/archimedes.0.4.19/

**Comment by Chris00** [comment]
In its current form, Archimedes will not be updated.  Some separate modules such as [Curve_sampling](https://github.com/Chris00/ocaml-curve-sampling) and [Color_brewery](https://github.com/Chris00/color_brewery) are under development and Archimedes may at some point be rebuild on top of these.
