### ISSUE TITLE
crash on macOS catalina

### ISSUE THREAD

**Issue by aryx** [Chris00/ocaml-cairo#18]
codemap from pfff (github.com/aryx/pfff) crashes on Catalina.
Here is the assertion failing:

Assertion failed: (!x_link_empty_p(&s->stack)), function CGGStackRestore, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreGraphics/CoreGraphics-1348.12.4.3/CoreGraphics/Context/CGGStack.c, line 74.
abort trap: 6

Have you seen something like that before?

My application is also using lablgtk2.

**Comment by Chris00** [comment]
> Have you seen something like that before?

Nope.  Do  you have a minimal example — with Cairo only (no Gtk)?

**Comment by Chris00** [comment]
@aryx The message you posted is not clearly linked to cairo and you did not provide more details.  Please reopen if you have a more complete report.
