### ISSUE TITLE
Image.get_stride does not behave as documented

### ISSUE THREAD

**Issue by FlorentHoareau** [Chris00/ocaml-cairo#3]
The generated documentation says :

val get_stride : Cairo.Surface.t -> int
Get the stride of the image surface in bytes.

But in the implementation, the stride is divided by 4 if the image is RGB24 or ARGB32, which is incorrect (the value returned by the underlying Cairo function is indeed the correct stride in bytes).
Shouldn't this behavior be reverted back to its original definition ? After all, the stride is used to compute the position of the beginning of a row ?

**Comment by Chris00** [comment]
I reverted the change but I have documented what was its intended goal in order to help the user.
