### ISSUE TITLE
Quartz module ?

### ISSUE THREAD

**Issue by dbuenzli** [Chris00/ocaml-cairo#6]
Is that supposed to be available on osx. It doesn't seem to be here. 

```
> opam info cairo2 -fversion
0.4.6
```

**Comment by dbuenzli** [comment]
Since cairo only [offers](http://cairographics.org/manual/cairo-Quartz-Surfaces.html) to operate from  a core graphics context (a very reasonable decision) it may not be that useful at the moment as I don't know any other OCaml library that can offer such a handle at the moment. It's also possible to operate on an in-memory bitmap but that's not very useful. 

However you may want to remove the mentions to unimplemented things from the library documentation.

**Comment by Chris00** [comment]
The other concern — orally mentioned — [has been addressed](http://cairo.forge.ocamlcore.org/tutorial/index.html) as well...
