### ISSUE TITLE
Does not compile on cygwin

### ISSUE THREAD

**Issue by Chimrod** [Chris00/ocaml-cairo#8]
Ocaml-cairo does not compile on cygwin. The setup search for includes in C:\… which does not make sense (cygwin use the same file organisation as any unix).

I've found the cause in [setup.ml:77](https://github.com/Chris00/ocaml-cairo/blob/master/setup.ml#L77) and [setup.ml:88](https://github.com/Chris00/ocaml-cairo/blob/master/setup.ml#L88)

The two functions should be replaced by those one :

```ocaml
let cairo_cflags =
  lazy(match cairo_cflags with
       | [] ->
         (match Sys.os_type with
          | "Cygwin"
          | "Unix" -> split_on_space(pkg_config "cairo" ["--cflags-only-I"])
          …

(** Compute the correct CLIBS for Cairo. *)
let cairo_clibs =
  lazy(match cairo_clibs with
       | [] ->
         (match Sys.os_type with
          | "Cygwin"
          | "Unix" -> split_on_space(pkg_config "cairo" ["--libs"])
          …
```

**Comment by Chris00** [comment]
In fact, `Sys.os_type` returns `Win32` on AppVeyor—so a more sophisticated decision has to be used...  (I'm working on it).

**Comment by Chris00** [comment]
It does now [pass the AppVeyor tests](https://ci.appveyor.com/project/Chris00/ocaml-cairo/build/1.0.39#L890).  Note that you will have to [install `lablgtk`](https://github.com/Chris00/ocaml-cairo/blob/master/appveyor.yml#L10) [for now](https://github.com/ocaml/oasis/issues/96).
